### ISSUE TITLE
Implement the mute button and toggle music button

### ISSUE THREAD

**Issue by theenergici** [GOUStudios/COVerIt-#72]
# Description 
right now we have 2 non functioning options, to toggle the sound and/ or music. 
we should implement them.
# TODOs
- [x] mute button mutes all sounds in the game
- [x] music toggle button turns music on and off
- [x] the buttons change appearance when they are activated
